<?php
/*
 * ImaxelAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/12/2015
 */

namespace ImaxelAPILib;

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'http://ips.1405.imaxel.com/WebCounterApi';

}
